apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: {{ .Release.Name }}-db
  type: {{ .Values.service.type }} 
  ports:
  - name: db
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}